---
title: "R Notebook"
output: html_notebook
---


regressionsgleichung aufstellen random

```{r}
model_1 <- lm(Umsatz ~ Wettercode + Bewoelkung + Windgeschwindigkeit + Temperatur + as.factor(Jahreszeit) + as.factor(Temperaturkategorie) + as.factor(Warengruppe) + Fussballspiel + Ferien + Feiertag  + KielerWoche + as.factor(Wochentag) + Flohmarkt + Kreuzfahrtschiffe, data = train_data)

model_2 <- lm(Umsatz ~ Wettercode + Bewoelkung + Windgeschwindigkeit + Temperatur * as.factor(Jahreszeit) * as.factor(Temperaturkategorie) + as.factor(Warengruppe) + Fussballspiel + Ferien + Feiertag  + KielerWoche + as.factor(Wochentag) + Flohmarkt + Kreuzfahrtschiffe, data = train_data)

model_3 <- lm(Umsatz ~ Wettercode + Bewoelkung + Windgeschwindigkeit + Temperatur * as.factor(Jahreszeit) * as.factor(Temperaturkategorie) + as.factor(Warengruppe) + Fussballspiel + Ferien * Feiertag  + KielerWoche + as.factor(Wochentag) + Flohmarkt + Kreuzfahrtschiffe, data = train_data)

model_4 <- lm(Umsatz ~ Wettercode + Bewoelkung + Windgeschwindigkeit + Temperatur * as.factor(Jahreszeit) * as.factor(Temperaturkategorie)+ as.factor(Warengruppe) + Fussballspiel + Ferien * Feiertag  + KielerWoche + as.factor(Wochentag) + Flohmarkt + Kreuzfahrtschiffe, data = train_data)

#Modelle mit valid_data
model_1v <- lm(Umsatz ~ Wettercode + Bewoelkung + Windgeschwindigkeit + Temperatur + as.factor(Jahreszeit) + as.factor(Temperaturkategorie) + as.factor(Warengruppe) + Fussballspiel + Ferien + Feiertag  + KielerWoche + as.factor(Wochentag) + Flohmarkt + Kreuzfahrtschiffe, data = valid_data)

model_2v <- lm(Umsatz ~ Wettercode + Bewoelkung + Windgeschwindigkeit + Temperatur * as.factor(Jahreszeit) * as.factor(Temperaturkategorie) + as.factor(Warengruppe) + Fussballspiel + Ferien + Feiertag  + KielerWoche + as.factor(Wochentag) + Flohmarkt + Kreuzfahrtschiffe, data = valid_data)

model_3v <- lm(Umsatz ~ Wettercode + Bewoelkung + Windgeschwindigkeit + Temperatur * as.factor(Jahreszeit) * as.factor(Temperaturkategorie) + as.factor(Warengruppe) + Fussballspiel + Ferien * Feiertag  + KielerWoche + as.factor(Wochentag) + Flohmarkt + Kreuzfahrtschiffe, data = valid_data)

model_4v <- lm(Umsatz ~ Wettercode + Bewoelkung + Windgeschwindigkeit + Temperatur * as.factor(Jahreszeit) * as.factor(Temperaturkategorie)+ as.factor(Warengruppe) + Fussballspiel + Ferien * Feiertag  + KielerWoche + as.factor(Wochentag) + Flohmarkt + Kreuzfahrtschiffe, data = valid_data)

#Berechne ein Regressionsmodell für den Umsatz für jede Warengruppe einzeln
model_W1 <- lm(Umsatz ~ Temperatur + Wettercode + Bewoelkung + Windgeschwindigkeit + Fussballspiel + Ferien + Feiertag  + KielerWoche + as.factor(Wochentag) + Flohmarkt, data = train_data %>% filter(Warengruppe == 1))
model_w2 <- lm(Umsatz ~ Temperatur + Wettercode + Bewoelkung + Windgeschwindigkeit + Fussballspiel + Ferien + Feiertag  + KielerWoche + as.factor(Wochentag) + Flohmarkt, data = train_data %>% filter(Warengruppe == 2))
model_w3 <- lm(Umsatz ~ Temperatur + Wettercode + Bewoelkung + Windgeschwindigkeit + Fussballspiel + Ferien + Feiertag  + KielerWoche + as.factor(Wochentag) + Flohmarkt, data = train_data %>% filter(Warengruppe == 3))
model_w4 <- lm(Umsatz ~ Temperatur + Wettercode + Bewoelkung + Windgeschwindigkeit + Fussballspiel + Ferien + Feiertag  + KielerWoche + as.factor(Wochentag) + Flohmarkt, data = train_data %>% filter(Warengruppe == 4))
model_w5 <- lm(Umsatz ~ Temperatur + Wettercode + Bewoelkung + Windgeschwindigkeit + Fussballspiel + Ferien + Feiertag  + KielerWoche + as.factor(Wochentag) + Flohmarkt, data = train_data %>% filter(Warengruppe == 5))
model_w6 <- lm(Umsatz ~ Temperatur + Wettercode + Bewoelkung + Windgeschwindigkeit + Fussballspiel + Ferien + Feiertag  + KielerWoche + as.factor(Wochentag) + Flohmarkt, data = train_data %>% filter(Warengruppe == 6))


```
Testen welches Modell das beste ist
```{r}
# Funktion zur Berechnung des mittleren absoluten Fehlers (MAE)
mae <- function(actual, predicted) mean(abs(actual - predicted))

models <- list(
  model_1 = predict(model_1),
  model_2 = predict(model_2),
  model_3 = predict(model_3),
  model_4 = predict(model_4)
)

# Berechnung des MAE für jedes Modell
mae_values <- lapply(models, function(pred) mae(train_data$Umsatz, pred))

# Zusammenfügen der Ergebnisse in eine Tabelle
result_table <- do.call(rbind, mae_values)

models_valid <- list(
  model_1v = predict(model_1v),
  model_2v = predict(model_2v),
  model_3v = predict(model_3v),
  model_4v = predict(model_4v)
)

# Berechnung des MAE für jedes Modell
mae_values_valid <- lapply(models_valid, function(pred) mae(valid_data$Umsatz, pred))

# Zusammenfügen der Ergebnisse in eine Tabelle
result_table_valid <- do.call(rbind, mae_values)
```


# versuche, den Datensatz für kaggle richtig hochzuladen


```{r}
# füge Datum und Warengruppe zu einer variable zusammen im Format 201801011 (01. Januar 2018, Warengruppe 1, entferne die Striche bei Datum)


valid_data$id <- paste0(valid_data$Datum, valid_data$Warengruppe)
# entferne die Striche bei Datum
valid_data$id <- gsub("-", "", valid_data$id)
levels_train <- levels(as.factor(train_data$Warengruppe))
levels_valid <- levels(as.factor(valid_data$Warengruppe))

# Überprüfen, ob die Stufen übereinstimmen
if (!identical(levels_train, levels_valid)) {
  # Wenn nicht, passen Sie die Stufen an oder fügen Sie fehlende Stufen hinzu
  valid_data$Warengruppe <- factor(valid_data$Warengruppe, levels = levels_train)
}
valid_data$Warengruppe <- factor(valid_data$Warengruppe, levels = levels_train)


```

## Füge eine Variable zu valid_data hinzu, die predUmsatz heißt und wo die vorhergesagten Umsätze stehen nach model_1

```{r}
levels(train_data$Jahreszeit)
levels(valid_data$Jahreszeit)
#Problembewältigung
unique(valid_data$Jahreszeit)
valid_data$Jahreszeit <- factor(valid_data$Jahreszeit, levels = c("Sommer", "Frühling", "Herbst", "Winter"))
levels(valid_data$Jahreszeit)
#Fehlende Werte werden gelöscht
valid_data <- na.omit(valid_data)
# Entferne die Gruppierung nach Jahreszeit
valid_data <- ungroup(valid_data)

# füge eine Variable zu valid_data hinzu, die predUmsatz heißt und wo die vorhergesagten Umsätze stehen

valid_data$predUmsatz <- predict(model_1, valid_data)


# erstelle einen neuen Datensatz, wo nur die Variablen id und predUmsatz drin sind
valid_data_pred <- valid_data %>% 
  select(id, predUmsatz) %>%
  rename(umsatz = predUmsatz)
# id solllte numerisch sein
valid_data_pred$id <- as.numeric(valid_data_pred$id)

# exportiere als .csv datei in github repository. seperate by comma und die predicted Umsatz Variable sollte "umsatz" heißen

write.csv(valid_data_pred, "valid_data_pred_model.csv", row.names = FALSE)


```
